In [1]:
import numpy as np
import pandas as pd

C:\Users\NARAYANA NALLAPU\anaconda3\Lib\site-packages\pandas\core\computation\expressions.py:22: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.10.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [3]:
s = pd.Series([10,20,30,40,])

In [4]:
print(s)

0    10
1    20
2    30
3    40
dtype: int64

In [5]:
pop = pd.Series([1444,1393,323,278],
                index = ["india","china","usa","indonasia"],
                name = "population_milliona"
               )

In [6]:
print(pop)

india        1444
china        1393
usa           323
indonasia     278
Name: population_milliona, dtype: int64

In [7]:
print(pop[pop>500])

india    1444
china    1393
Name: population_milliona, dtype: int64

In [9]:
q1 = pd.Series({"laptop": 120,"phone": 340, "table": 77})
q2 = pd.Series({"phone": 120,"laptop": 474, "watches": 32})
print(q1+q2)

laptop     594.0
phone      460.0
table        NaN
watches      NaN
dtype: float64

In [10]:
##data frMES##

In [26]:
df = pd.DataFrame({
    "name" : ["Asha","Bill","Chen","Diya","Evan"],
    "dept" : ["iT","HR","FINANCE","IT","HR"],
    "salary" : [52000,48000,47999,75000,50000],
    "city" : ["Delhi","Mumbai","Surat","Agra","Delhi"]
})

In [27]:
print(df)

   name     dept  salary    city
0  Asha       iT   52000   Delhi
1  Bill       HR   48000  Mumbai
2  Chen  FINANCE   47999   Surat
3  Diya       IT   75000    Agra
4  Evan       HR   50000   Delhi

In [19]:
raw = pd.DataFrame({
    "order_id": ["1001","1002","1003",],
    "amount": ["2500","1800","3200"]
})

In [21]:
print(raw["amount"].sum())

250018003200

In [28]:
clean = raw.copy()

In [29]:
clean["order_id"] = pd.to_numeric(clean["order_id"])
clean["amount"] = pd.to_numeric(clean["amount"])

In [31]:
print(clean["amount"].sum())

7500

In [32]:
df

   name     dept  salary    city
0  Asha       iT   52000   Delhi
1  Bill       HR   48000  Mumbai
2  Chen  FINANCE   47999   Surat
3  Diya       IT   75000    Agra
4  Evan       HR   50000   Delhi

In [35]:
people = df.set_index("name")

In [36]:
people

         dept  salary    city
name
Asha       iT   52000   Delhi
Bill       HR   48000  Mumbai
Chen  FINANCE   47999   Surat
Diya       IT   75000    Agra
Evan       HR   50000   Delhi

In [46]:
print(people.loc["Bill"])

dept          HR
salary     48000
city      Mumbai
Name: Bill, dtype: object

In [47]:
print(people.loc[["Bill"],["salary"]])

      salary
name
Bill   48000

In [52]:
print(people.iloc[1])

dept          HR
salary     48000
city      Mumbai
Name: Bill, dtype: object

In [58]:
print(people.iloc[0:3],[0,2])

         dept  salary    city
name
Asha       iT   52000   Delhi
Bill       HR   48000  Mumbai
Chen  FINANCE   47999   Surat [0, 2]

In [57]:
print(people[people["salary"] < 49000])

         dept  salary    city
name
Bill       HR   48000  Mumbai
Chen  FINANCE   47999   Surat

In [65]:
print(people[(people["dept"] == "IT") & (people["salary"] < 49000)])

Empty DataFrame
Columns: [dept, salary, city]
Index: []

In [68]:
print(people.query('dept == "IT"'))

     dept  salary  city
name
Diya   IT   75000  Agra

##missing data##

In [79]:
messy = pd.DataFrame({
    "product" :["pen","book","bag","lamp","moug"],
                     "price": [20,np.nan, 850,1200, np.nan],
"rating": [4.1,4.5,np.nan,4.5,3.9]
})

In [80]:
messy

  product   price  rating
0     pen    20.0     4.1
1    book     NaN     4.5
2     bag   850.0     NaN
3    lamp  1200.0     4.5
4    moug     NaN     3.9

In [81]:
messy.isna().sum()

product    0
price      2
rating     1
dtype: int64

In [82]:
filled = messy.copy()

In [83]:
filled["price"] = filled["price"].fillna(filled["price"].mean())

In [84]:
filled["rating"] = filled["rating"].fillna(filled["rating"].mean())

In [85]:
print(filled)

  product   price  rating
0     pen    20.0    4.10
1    book   690.0    4.50
2     bag   850.0    4.25
3    lamp  1200.0    4.50
4    moug   690.0    3.90